import Head from 'next/head'
import {Container} from '@mui/material'
import StocksContainer from '../components/stocksContainer'

export default function Home() {

  return (
    <Container maxWidth='lg'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StocksContainer>
        </StocksContainer>
    </Container>
  )
}
