import Head from 'next/head'
import { Container, Paper } from '@mui/material'
import PortfolioPanel from '../components/PanelPortfolio/PortfolioPanel'
import MarketPanel from '../components/PanelMarket/MarketPanel'
import ActionPanel from '../components/ActionPanel'
import { useEffect, useState } from 'react'
import api from '../api'
import { Query } from 'appwrite'

export default function Home() {
  const [open, setOpen] = useState(false)
  const [focuseStock, setFocuseStock] = useState()
  const [assets, setAssets] = useState([])
  const [stocks, setStocks] = useState([])

  const fetchStocksAndAssets = async () => {
    const user = await api.account.get()
    const { documents: dataFromServerAssets } = await api.database.listDocuments('asset', [Query.equal('ownerId', user.$id)])
    const { documents: dataFromServerStocks } = await api.database.listDocuments('stock')
    setAssets(dataFromServerAssets)
    setStocks(dataFromServerStocks)
  }
  const handleChangeFocus = (stock) => {
    // console.log(stock)
    setOpen(true)
    setFocuseStock(stock)
  }
  useEffect(() => {
    let interval
    if (stocks) {
      interval = setInterval(async () => {
        const { documents: dataFromServerStocks } = await api.database.listDocuments('stock')
        setStocks(dataFromServerStocks)

      }, 10000)
    }
    return () => clearInterval(interval)
  }, [])
  useEffect(() => {
    fetchStocksAndAssets()
  }, [])

  return (
    <Container maxWidth='xl'>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/> 
      </Head>
      <>
        <Paper sx={{p:2, backdropFilter: 'blur(20px)',backgroundColor:'transparent',position:'static' }}>
          <PortfolioPanel stocks={stocks} assets={assets} />
          <MarketPanel stocks={stocks} setFocuseStock={handleChangeFocus} />
        </Paper>
        {focuseStock && <ActionPanel open={open} setOpen={setOpen} stockId={focuseStock.$id} />}

      </>
    </Container>
  )
}
